# Generated by Django 3.2.14 on 2022-07-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date Type')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Value')),
            ],
        ),
        migrations.CreateModel(
            name='OnDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Value')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Value')),
            ],
        ),
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Name')),
            ],
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relation', models.BooleanField(blank=True, default=False, null=True)),
                ('related_table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Related Table Name')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Name')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verbose Name')),
                ('field_length', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field Length')),
                ('nullable', models.BooleanField(blank=True, null=True)),
                ('blankable', models.BooleanField(blank=True, null=True)),
                ('data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_type_table', to='MainApp.datatype')),
                ('default_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_value_table', to='MainApp.defaultvalue')),
                ('on_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_delete_table', to='MainApp.ondelete')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_table', to='MainApp.relationshiptype')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_table', to='MainApp.tablename')),
            ],
        ),
    ]
