# Generated by Django 3.2.14 on 2023-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Age')),
            ],
        ),
        migrations.DeleteModel(
            name='PhishingModel',
        ),
    ]
