# Generated by Django 3.2.14 on 2023-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableCreation', '0002_auto_20230530_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.TextField(verbose_name='Password')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
            ],
        ),
        migrations.DeleteModel(
            name='FirstTableModel',
        ),
    ]
