# Generated by Django 3.2.14 on 2023-05-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TableCreation', '0004_auto_20230530_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TableCreation.firsttablemodel')),
            ],
        ),
    ]
