# Generated by Django 3.2.14 on 2023-05-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableCreation', '0005_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttablemodel',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
