# Generated by Django 3.2.14 on 2022-08-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('IP_Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP Address')),
            ],
        ),
    ]
